<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mt</string>
	</array>
	<key>name</key>
	<string>Monte</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>#.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.monte</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(def)\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.monte</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.monte</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)\s*:|\{</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(to)\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.method.monte storage.type.function.monte</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.method.monte entity.name.function.monte</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)\s*:</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(if|else|match|switch|while)\b</string>
			<key>name</key>
			<string>keyword.control.flow.conditional.monte</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(for|while)\b</string>
			<key>name</key>
			<string>keyword.control.flow.loop.monte</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(try|catch|escape|finally)\b</string>
			<key>name</key>
			<string>keyword.control.flow.exception.monte</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(return|break|continue|exit)\b</string>
			<key>name</key>
			<string>keyword.control.flow.ejectors.monte</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(as)\b</string>
			<key>name</key>
			<string>keyword.operator.monte</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(in|pass)\b</string>
			<key>name</key>
			<string>keyword.other.monte</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(extends|guards|implements|via)\b</string>
			<key>name</key>
			<string>storage.modifier.monte</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(method|fn|to)\b</string>
			<key>name</key>
			<string>storage.type.function.monte</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(interface|object)\b</string>
			<key>name</key>
			<string>storage.type.object.monte</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(def)\b</string>
			<key>name</key>
			<string>storage.type.immutable.monte</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(var)\b</string>
			<key>name</key>
			<string>storage.type.mutable.monte</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(any|boolean|char|float|int|void)\b</string>
			<key>name</key>
			<string>storage.modifier.guard.monte</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Literal constants</string>
			<key>match</key>
			<string>\b(true|false|null)\b</string>
			<key>name</key>
			<string>constant.language.monte</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Literal floats</string>
			<key>match</key>
			<string>\b([0-9]+\.([0-9]+)?)|(([0-9]+)\.[0-9]+)\b</string>
			<key>name</key>
			<string>constant.numeric.float.monte</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Literal ints</string>
			<key>match</key>
			<string>\b([0-9]+|0x[0-9a-fA-F]+)\b</string>
			<key>name</key>
			<string>constant.numeric.integer.monte</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.monte</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Literal double quoted strings</string>
			<key>end</key>
			<string>(?&lt;!\\)(")</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.monte</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.monte</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.monte</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Literal single quoted strings</string>
			<key>end</key>
			<string>(?&lt;!\\)'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.monte</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.monte</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.monte</string>
				</dict>
			</dict>
			<key>end</key>
			<string>`</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.monte</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.backtick.monte</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[$@]\w+</string>
					<key>name</key>
					<string>variable.other.monte</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>[$@]{</string>
					<key>end</key>
					<string>}</string>
					<key>name</key>
					<string>variable.other.monte</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\*\*|\*|//|/|%%|%|\+|\-|&lt;&lt;|&gt;&gt;|\.\.!|\.\.</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.monte</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;=&gt;|&gt;=|&lt;=|&gt;|&lt;|==|!=</string>
			<key>name</key>
			<string>keyword.operator.comparison.monte</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=~|!~</string>
			<key>name</key>
			<string>keyword.operator.pattern.monte</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&amp;&amp;|\|\|</string>
			<key>name</key>
			<string>keyword.operator.logical.monte</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&amp;!|\^|&amp;|\|</string>
			<key>name</key>
			<string>keyword.operator.bitwise.monte</string>
		</dict>
		<dict>
			<key>match</key>
			<string>:=</string>
			<key>name</key>
			<string>keyword.operator.assignment.monte</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\*\*|\*|//|/|%%|%|\+|\-|&lt;&lt;|&gt;&gt;|\.\.!|\.\.|&amp;&amp;|&amp;!|&amp;|\|\||\||^)=</string>
			<key>name</key>
			<string>keyword.operator.assignment.augmented</string>
		</dict>
		<dict>
			<key>match</key>
			<string> =[^~=&gt;]</string>
			<key>name</key>
			<string>illegal.invalid.bad-assignment.monte</string>
		</dict>
		<dict>
			<key>match</key>
			<string>trace(ln)?</string>
			<key>name</key>
			<string>support.function.python</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.monte</string>
	<key>uuid</key>
	<string>635C76EE-711C-455D-A065-2E52C3106B9D</string>
</dict>
</plist>
