# Switch to faster container-based builders. Forbids use of sudo, setuid,
# seteid, etc. but we don't need them.
sudo: false
language: python
python:
    - '2.7'
    - pypy

matrix:
    allow_failures:
        - python: pypy
    fast_finish: true

script:
    - bin/tests

notifications:
    email: false
    irc:
        channels:
            - "chat.freenode.net#monte"
        on_success: change
        on_failure: always
