language: python
python:
    - '2.7'
    - pypy

matrix:
    allowed_failures:
        - pypy

env:
    - PYTHON_TESTS=true MONTE_TESTS=false
    - PYTHON_TESTS=false MONTE_TESTS=true

script:
    - if $PYTHON_TESTS; then; trial monte; fi
    - if $MONTE_TESTS; then; bin/monte-tests; fi

notifications:
    email: false
    irc:
        channels:
            - "chat.freenode.net#monte"
        on_success: always
        on_failure: always

